### PR TITLE
Add mouse system cursors

### PR DESCRIPTION
**Pull request by seyhajin**
Use I-Beam cursor with TextView (for Ted2/Ted2Go editor)

### CODE REVIEW

**Comment by blitz-research** [comment]
Has this been tested on windows/macos/linux?

**Comment by seyhajin** [comment]
Hi Mark,

I have been tested on Windows 10 and MacOS Sierra. I suppose that work on Linux (SDL2). 
The code has been updated since, I had error message output of the application in particular because of the call of the function "libc.atexit", I parameterized a method instead of a function . I will return this new code if you wish.

https://github.com/seyhajin/monkey2/blob/master/modules/mojo/input/mouse.monkey2#L227

**Comment by blitz-research** [comment]
Ok, I've manually merged the Mouse device stuff so far, because I suck at git. Works well though and is a useful addition, thanks!

Mojox changes up next, but I might have a think about adding a View.Pointer property first...

**Comment by seyhajin** [comment]
Good news!
And you're right, for a better integration of the cursor in Mojox, the property must be present in the View class (View.Pointer) and derived if necessary another method (or Lambda?) depending on the events / states of the widget.

**Pull request closed without merging**
