### PR TITLE
Added ability to show/hide lines in TextView (needed for folding).

### PR DESCRIPTION
**Pull request by engor**

### CODE REVIEW

**Comment by engor** [comment]
Changes are about hiding lines. These changes are needed for folding stuff.

(Also I fixed many whitespaces in file.)

**Comment by blitz-research** [comment]
Can you give me a quick rundown on how this actually works?

I would have thought (but have never tried) you could do code folding by replacing "~n" chars in a block with a special hidden char, but that's probably too easy!

**Comment by engor** [comment]
In my CodeTextView - hide needed lines so they don't occupy space in editor and skipped on render.
Special char - maybe it will work and is much easier.

**Comment by engor** [comment]
And with special char - if you open such file in other editor file will looks broken?

**Comment by blitz-research** [comment]
You'd never save with special char...but it was just an idea, would like to
know your approach.

On Sun, Mar 25, 2018 at 2:56 PM, Evgeniy Goroshkin <notifications@github.com

**Comment by engor** [comment]
I copied mojo.TextView with my additions into ted2go and it works fine w/o identifiers collisions, thanks for namespaces.

**Pull request closed without merging**
